on: [push, pull_request]
name: build
jobs:

  test:
    strategy:
      matrix:
        go-version: [1.24.x, 1.25.x]
        os: [ubuntu-24.04, macos-13, windows-latest]
        targetplatform: [x86, x64]

    runs-on: ${{ matrix.os }}

    steps:

    - name: Install Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ matrix.go-version }}
        cache: false

    - name: Checkout code
      uses: actions/checkout@v6

    - name: Get dependencies
      run: |
        env GO111MODULE=on go vet ./...
    - name: Build
      run: go build -v .

    - name: Build on ARM
      if: runner.os == 'Linux'
      run: |
        GOARCH=arm GOARM=5 go build .
        GOARCH=arm GOARM=6 go build .
        GOARCH=arm GOARM=7 go build .
        GOARCH=arm64 go build .
        GOARCH=arm64 GOOS=android go build .

    - name: Unit tests (-short, coverage)
      shell: bash
      env:
        GOCACHE: ${{ runner.temp }}/go-build
      run: |
        set -euo pipefail
        pkgs=$(go list ./... | grep -v 'github.com/xuri/excelize/v2/tests/manual/tools')
        env GO111MODULE=on go test -short ${pkgs} -coverprofile='coverage.txt' -covermode=atomic

    - name: Race tests
      shell: bash
      run: |
        set -euo pipefail
        pkgs=$(go list ./... | grep -v 'github.com/xuri/excelize/v2/tests/manual/tools')
        env GO111MODULE=on go test -v -timeout 60m -race ${pkgs}

    - name: Codecov
      uses: codecov/codecov-action@v5
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        files: coverage.txt
        flags: unittests
        name: codecov-umbrella
